### ISSUE TITLE
Unable to output a whitespace only string using `fy_emit_vevent`

### ISSUE THREAD

**Issue by kdubb** [pantoniou/libfyaml#109]
I cannot find a way to write a whitespace-only string of any length using `fy_emit_vevent`. It always outputs an empty string. Different styles output their specific version of an empty string.

I've tried in both `FYECF_DEFAULT` and `FYEFC_PRETTY` modes with the same result.

After much debugging, I've only been able to glean that it thinks it should be stripping whitespace from the string, regardless of style or mode.

**Comment by kdubb** [comment]
I added the following as `scalar-space2.yaml` to the `emitter-examples` directory:
```yaml
0: " "
a: "  "
i: "        "
```

It seems to pass the test, but I have yet to work out how the `fy-tool` testing actually works.

**Comment by kdubb** [comment]
Also, note that I am emitting using the streaming emitter functionality.

**Comment by pantoniou** [comment]
This is fixed, so closing.
