### ISSUE TITLE
Does fy-tool allow modifying and deleting keys?

### ISSUE THREAD

**Issue by hq6** [pantoniou/libfyaml#114]
The [documentation](https://pantoniou.github.io/libfyaml/man/fy-tool.html) states a `filter` option, but there are no examples of replacing the value for a key with another, or deleting an entire key or set of keys by regex or glob pattern.

Is there support for these operations in either the library or the tool?

I'm looking for functionality similar to what [yq](https://github.com/mikefarah/yq) supports, but without messing up formating like `yq` does.

**Comment by pantoniou** [comment]
Fixed in 13fc5ac6e4f0362cdd982875dbfd2e51091126b2

**Comment by hq6** [comment]
@pantoniou Thanks for fixing the library!

However, I'm still interested in whether the CLI tool supports this out of the box.

Could you address  this question explicitly either here or in the docs?

**Comment by pantoniou** [comment]
There's a WIP ypath implementation using the --ypath switch.
It's quite experimental right now, and although it supports expressions, it doesn't support negation yet for filtering out nodes.

I might be able to take a stab at what you want, what kind of yq subset do you need?
Note that the syntax will be different.

**Comment by hq6** [comment]
I don't really need the fancy transformations. Just the following would make it super useful:
1. Be able to delete keys whose path matches either glob or regex pattern. 
    * Example: Delete all keys at paths matching "metadata.annotations.*".
2. Be able to delete items in a sequence either by index, or which satisfies some condition:
    * Example: Delete the items of `spec.containers[0].env` which have a key called `name` and a value called `HTTP_PROXY`.
3. Be able to upsert the value at arbitrary paths, creating parents as needed, and replacing if already exists.
