### ISSUE TITLE
Compilation problem with -fvisibility=hidden

### ISSUE THREAD

**Issue by CB750-Rider** [pantoniou/libfyaml#13]
If the gcc option [`-fvisibility=hidden`](https://gcc.gnu.org/onlinedocs/gcc-9.2.0/gcc/Code-Gen-Options.html#Code-Gen-Options) is set as part of `CFLAGS` when compiling, libfyaml's `make all` fails when attempting to link [fy-tool](https://github.com/pantoniou/libfyaml/blob/master/src/tool/fy-tool.c). A work-around is to add the lines
```c
#if __GNUC__ >= 4
    #pragma GCC visibility push(default)
#endif
```
to [`libfyaml.h`](https://github.com/pantoniou/libfyaml/blob/master/include/libfyaml.h). This makes sure that the public functions are not hidden by the `-fvisibility=hidden` flag. 

Thanks for developing the library. It is working great!

**Comment by pantoniou** [comment]
The hidden visibility thing was on my TODOs, so you've managed to push it to the top.
Just pushed a change that compiles the library with -fvisibility=hidden by default (if that's supported by the compiler).

It should address your problem. Cheers.

**Comment by CB750-Rider** [comment]
Thanks for putting that fix in!
