### ISSUE TITLE
unprintable characters in anchor names causes failure

### ISSUE THREAD

**Issue by babywonderland** [pantoniou/libfyaml#15]
When this file: [anchortest.txt](https://github.com/pantoniou/libfyaml/files/4158807/anchortest.txt)
... is given to fy-tool, the expected output should be close to the input. Instead, the output seems to be truncated:
>     %YAML 1.1
>     ---
>     - !!tagaaa
>       name: somename1
>       somekey1:
>         - !!tagbbb
>           somekey2: !!tagccc
>             groups:
>               - &group_

If the non-printable characters in the anchor name are replaced with something innocuous like `_`, (as in this file: [anchortest_clean.txt](https://github.com/pantoniou/libfyaml/files/4158806/anchortest_clean.txt)), then the output is as expected:
>     %YAML 1.1
>     ---
>     - !!tagaaa
>       name: somename1
>       somekey1:
>         - !!tagbbb
>           somekey2: !!tagccc
>             groups:
>               - &group_____QMCEQMTN_AGMOQDA_B1_rsan`ps._agmoQda/ !!group
>                 name: "óà\x8A¼QMCEQMTN\x1FAGMOQDA\x1FB1\x1Ersan`ps.\x1FagmoQda/"
>     - !!tagaaa
>       name: end
>     ...

**Comment by pantoniou** [comment]
Should be addressed in 8f78586262fded39988de630688fed03dc80d9f7

Verify it works so that I can close the issue.
