### ISSUE TITLE
String values starting with & must be quoted

### ISSUE THREAD

**Issue by babywonderland** [pantoniou/libfyaml#16]
When creating a scalar node that starts with &, libfyaml does not quote or escape the string value. When subsequently parsed, the value is mistaken for an anchor. See [attached test case](https://github.com/pantoniou/libfyaml/files/4207037/test.txt) (change extension from .txt to .cpp).

The relevant bits of the test case:
...
`fy_node* val1 = fy_node_create_scalar(fydoc, "&Hello \"Value1\"", -1);`
...
`fy_emit_document_to_file(fydoc, flags, yaml_file);`
...
`fy_document_build_from_file(&fypcfg, yaml_file);`
...
`const char* nodeval = fy_node_get_scalar(val1, &nodeval_len);`
`if (nodeval =="&Hello \"Value1\"") { print "PASS"; } else { print "FAIL"; }`

**Comment by pantoniou** [comment]
Addressed in c3472c0ba872b43514ba61121ea78036650c3f6c

Verify and then we'll close this issue.

**Comment by pantoniou** [comment]
fixed.
