### ISSUE TITLE
Handling tabs to support DT YAML binding docs

### ISSUE THREAD

**Issue by ohporter** [pantoniou/libfyaml#2]
I think something useful to the DeviceTree community would be a **fy_parse_cfg_flags** option that supports handling tabs. One of the limitation of the DT binding docs in YAML is that with existing parsers, one can not leave the usual tabs in the example usage (typically copied from a kernel .dts file with spaces). Something like **FYPCF_ENABLE_TABS** could engage digestion of tabs for this case.

**Comment by ingydotnet** [comment]
YAML doesn't support tabs for indentation. I advise against this.

**Comment by pantoniou** [comment]
It doesn't seem awfully hard to do, at least for some quick tests it seems to work.

[x.txt](https://github.com/pantoniou/libfyaml/files/3625868/x.txt)

This small snippet with mixed tab/spaces indent work (with --tab = 8)

I should note that block scalars with explicit indents may not work, but that's not something you
usually see in the wild.

**Comment by pantoniou** [comment]
Support for tabs has been merged in master now; it will be disabled by default (it gets automatically enabled when a vim cmd line is encountered with a tab option).

Note that mixing spaces and tab indentation is tricky to get right, especially with block literals/folded scalars, so try not to do that.
