### ISSUE TITLE
Add CMake build system?

### ISSUE THREAD

**Issue by jlblancoc** [pantoniou/libfyaml#25]
It would be great to have this awesome project ported to CMake, for easier integration with other tools, and probably as a first step to solve #10 too.

My initial attempt (working for the library itself for now) is here, for your reference: https://github.com/MRPT/libfyaml/commit/75addc8ec95a55eeb9339519d28f85887b748bc2

**Comment by stilgarpl** [comment]
@jlblancoc This cmake file looks good, but you should add CONFIGURE_DEPENDS flag to your file(GLOB*), so that it could correctly find files that were changed after the first build.

**Comment by jlblancoc** [comment]
Awesome! I didn't know the flag CONFIGURE_DEPENDS. It was apparently added to CMake >= 3.12.

**Comment by pantoniou** [comment]
I'm merging this. It's been a long time in my TODOs but never got enough time to do it.
If you could please add some rules to build fy-tool it would be appreciated.

Thanks a bunch!
