### ISSUE TITLE
Stream output support

### ISSUE THREAD

**Issue by kdubb** [pantoniou/libfyaml#28]
Is there a way to stream output?  I attempted to by creating and `fy_event` manually, but there appears to be no way to create tokens.

**Comment by cruisercoder** [comment]
This is unclear to me as well as to how you emit individual events.  It looks like it's coupled with the parser.

**Comment by pantoniou** [comment]
As of 246fb50b55ac3ca961bf1679d6805cb2b286afde it is now possible to create events.

I assume this is for foreign language bindings. So TL;DR it is now supported, go wild.
