### ISSUE TITLE
`#warn` is an invalid preprocessing directive

### ISSUE THREAD

**Issue by nektro** [pantoniou/libfyaml#30]
https://github.com/pantoniou/libfyaml/blob/cd04f85/src/lib/fy-parse.c#L40
```
error(compilation): clang failed with stderr: ./libfyaml/src/lib/fy-parse.c:40:2: error: invalid preprocessing directive
```

**Comment by nisalb** [comment]
I assume this is a typo. The author must have meant the `#warning` directive. Isn't it?

**Comment by nektro** [comment]
https://gcc.gnu.org/onlinedocs/cpp/Diagnostics.html

yes, there is `#error` and `#warning`.

**Comment by pantoniou** [comment]
Known issue, will fix, however the real problem is that VERSION is not defined. This used to happen when using tarballs from github.

Are you sure this happens on master?

**Comment by nektro** [comment]
That was my bad then, at the time I was writing a custom build script and just totally missed that defining `VERSION` would've fixed it.

**Comment by pantoniou** [comment]
> That was my bad then, at the time I was writing a custom build script and just totally missed that defining `VERSION` would've fixed it.

No worries.

I know of the bogus #warn but left it there so I can catch the undefined VERSION problem, it used to be happening quite often.

Cheers...

**Comment by pantoniou** [comment]
77fb75287a17f0c55728eb80ababfaf1a50ca36d fixes that.
