### ISSUE TITLE
stdin based input does too much buffering

### ISSUE THREAD

**Issue by hapejot** [pantoniou/libfyaml#34]
I am using the stdin based input for reading a sequence of documents.
These documents are produced in another program that pipes the result to the next program.

My problem right now is that the output on stdout is flushed without problem, but the receiving program does to good a job in buffering the input. I am passing several tiny documents before the first one is even recognized by the parser.

Question is, why is the buffering done anyway? the stdio functions already have a buffering and some standard ways to tweak it. So fyaml doesn't need to add another layer of buffer in my opinion. For my purposes I am removed the buffering and it worked fine.

**Comment by pantoniou** [comment]
Looks like you're doing streaming mode input. If latency is your main concern you should use that.

There's nothing stopping you adding a special non-buffering mode as an input mode, and patches would be welcome.
