### ISSUE TITLE
Problem configuring release 0.5.7

### ISSUE THREAD

**Issue by lackyO3** [pantoniou/libfyaml#35]
I get an odd result when trying to install from libfyaml-v0.5.7.tar.gz
which doesn't happen when I use libfyaml-0.5.5.tar.gz.

The build is on CentOS 7. I believe I'm following identical steps for each.

When I configure version 0.5.5 I get this:

 ```
---{ libfyaml 0.5.5 }---

    VERSION:               0.5.5
    MAJOR.MINOR:           0.5
    PATCH:                 5
    EXTRA:                 0.5.5
.
.
.

```
However when I configure version 0.5.7 I get this:

```
---{ libfyaml UNKNOWN }---

    VERSION:               UNKNOWN
    MAJOR.MINOR:           UNKNOWN.UNKNOWN
    PATCH:                 UNKNOWN
    EXTRA:                 UNKNOWN

```
As a result when I install the libraries the file names are incorrect:

for example:

libfyaml-UNKNOWN.UNKNOWN.a

I am not experienced developing with autoconf but I've installed many
packages that use it and I've never seen this before.

**Comment by pantoniou** [comment]
Use https://github.com/pantoniou/libfyaml/releases/download/v0.6.1/libfyaml-0.6.1.tar.gz

I.e. only the release tarballs that are manually uploaded. The tarball that github produces are broken re: versioning.

I'm trying to figure out, if there's a way to fix them, but in the meantime, always use the manually generated release tarballs.
