### ISSUE TITLE
fy_emit_event_vcreate doesn't set type

### ISSUE THREAD

**Issue by kdubb** [pantoniou/libfyaml#38]
`fy_event.type` is never set by the event create method.

**Comment by kdubb** [comment]
Thank you for the new API 🎉

**Comment by pantoniou** [comment]
Err, which branch are you looking at. In master branch at fy-event.c line 239:  fye->type = type;

**Comment by pantoniou** [comment]
Oops, there was indeed a patch missing... should be okay now.
