### ISSUE TITLE
bootstrap.sh fails on not-latest aclocal

### ISSUE THREAD

**Issue by rsbeckerca** [pantoniou/libfyaml#51]
I'm getting a bad symbol error on HPE NonStop when running bootstrap.sh:

```
configure.ac:99: error: possibly undefined macro: AC_LTDL_ENABLE_INSTALL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

I am running autoconf 2.69.

**Comment by pantoniou** [comment]
Looks like it's an libtool issue.

Remove the line in the configure.ac file and try again.

I think it should work, but I don't have access to your kind of system to verify.

**Comment by rsbeckerca** [comment]
> Looks like it's an libtool issue.
> 
> Remove the line in the configure.ac file and try again.
> 
> I think it should work, but I don't have access to your kind of system to verify.

Commenting that line moves past that issue, but then configure fails on:

`./configure[21058]: syntax error at line 21058 : `(' unexpected`

I was unaware that `yaml-0.1` was a dependency.

**Comment by pantoniou** [comment]
Just remove the line completely, don't comment it out with #

There is no hard dependency, it is an optional dependency.

**Comment by rsbeckerca** [comment]
There are just too many issues in configure for me to hack. Sorry, I'm giving up on this package for now.
