### ISSUE TITLE
Double free

### ISSUE THREAD

**Issue by vitenti** [pantoniou/libfyaml#74]
I'm getting a double free error. Debugging the code I got to line 198 of fy-doc.c:

```
	if (data_copy)
		fyi = fy_input_from_malloc_data((void *)text, len, &handle, true);
```

I suppose that should read:

```
	if (data_copy)
		fyi = fy_input_from_malloc_data((void *)data_copy, len, &handle, true);
```

**Comment by pantoniou** [comment]
I believe this is fixed by 618589b1d914d2cbc4053c9b1cbdcbc1e8d05d8c
