### ISSUE TITLE
JSON dump issues

### ISSUE THREAD

**Issue by cemerick** [pantoniou/libfyaml#8]
There seem to be a number of issues with the JSON output provided by `fy-tool`. e.g. given an input file `x.yml` of:

```yaml
foo: 
bar: a\s+b
```

a simple dump command of `src/fy-tool -m json x.yml` yields

```json
{
  "foo": ,
  "bar": "a\s+b"
}
```

...which isn't JSON for two reasons:

1. the value of `foo` should be a `null` literal
2. the backslash in `bar`'s string isn't escaped properly.

**Comment by pantoniou** [comment]
ACK, will look into it.

**Comment by cemerick** [comment]
Confirmed that these issues are fixed on master, thanks :-)
