### ISSUE TITLE
Attempting to dump unresolved aliases to JSON should yield a failure / nonzero exit

### ISSUE THREAD

**Issue by cemerick** [pantoniou/libfyaml#9]
Given

```yaml
foo: &foo 5
bar: *foo
```

`libfyaml/src/fy-tool -m json foo.yaml` yields:

```json
{
  "foo": 5,
  "bar": "foo"
}
```

I would expect an error message and nonzero exit code when attempting to emit JSON corresponding to any input YAML that contains unresolved aliases.

(Note that alias resolution when emitting JSON appears to work just fine.)

**Comment by pantoniou** [comment]
You will now get an error, so closing.

foo.yaml:2:7: error: aliases not allowed in JSON emit mode
bar: *foo
      ^~~
