### ISSUE TITLE
`fy_document_scanf' can not return the complete string including spaces.

### ISSUE THREAD

**Issue by liyanrui** [pantoniou/libfyaml#95]
Here is a minimum example. 

foo.yaml:

```yaml
text: "hello yaml!"
```

foo.c:

```c
#include <stdio.h>
#include <stdlib.h>
#include <libfyaml.h>

int main(void) {
        struct fy_document *fyd = fy_document_build_from_file(NULL, "foo.yaml");
        char text[256 + 1];
        int count = fy_document_scanf(fyd, "/text %256s", text);
        if (count != 1) {
                fprintf(stderr, "Failed to retreive the item!\n");
                exit(EXIT_FAILURE);
        }
        printf("text: %s\n", text);
        fy_document_destroy(fyd);
        return 0;
}
```

This program outputs

```
text: hello
```

**Comment by q962** [comment]
https://github.com/pantoniou/libfyaml/blob/ce5149953e043541fb7ecca21691423aaad90513/src/lib/fy-doc.c#L6280

Unfortunately, no specific treatment is given.
I am expecting two options
- `%s` copy data
- `%@s` pointer (maybe, pass two values, one accepting the string length and the other accepting the string address)

In fact, even if a width specifier is provided for `%s`, it is still impossible to include whitespace
https://en.cppreference.com/w/c/io/fscanf

**Comment by q962** [comment]
🤯 

use `%<number>c`

The description of %c is very clear, but I didn't notice it
